/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as StudyRouteImport } from './routes/study'
import { Route as DecksRouteImport } from './routes/decks'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicNewRouteImport } from './routes/topic.new'
import { Route as TopicIdRouteImport } from './routes/topic.$id'

const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksRoute = DecksRouteImport.update({
  id: '/decks',
  path: '/decks',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicNewRoute = TopicNewRouteImport.update({
  id: '/topic/new',
  path: '/topic/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicIdRoute = TopicIdRouteImport.update({
  id: '/topic/$id',
  path: '/topic/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/decks': typeof DecksRoute
  '/study': typeof StudyRoute
  '/tags': typeof TagsRoute
  '/topic/$id': typeof TopicIdRoute
  '/topic/new': typeof TopicNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/decks': typeof DecksRoute
  '/study': typeof StudyRoute
  '/tags': typeof TagsRoute
  '/topic/$id': typeof TopicIdRoute
  '/topic/new': typeof TopicNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/decks': typeof DecksRoute
  '/study': typeof StudyRoute
  '/tags': typeof TagsRoute
  '/topic/$id': typeof TopicIdRoute
  '/topic/new': typeof TopicNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/decks'
    | '/study'
    | '/tags'
    | '/topic/$id'
    | '/topic/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/decks'
    | '/study'
    | '/tags'
    | '/topic/$id'
    | '/topic/new'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/decks'
    | '/study'
    | '/tags'
    | '/topic/$id'
    | '/topic/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  DecksRoute: typeof DecksRoute
  StudyRoute: typeof StudyRoute
  TagsRoute: typeof TagsRoute
  TopicIdRoute: typeof TopicIdRoute
  TopicNewRoute: typeof TopicNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks': {
      id: '/decks'
      path: '/decks'
      fullPath: '/decks'
      preLoaderRoute: typeof DecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/new': {
      id: '/topic/new'
      path: '/topic/new'
      fullPath: '/topic/new'
      preLoaderRoute: typeof TopicNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/$id': {
      id: '/topic/$id'
      path: '/topic/$id'
      fullPath: '/topic/$id'
      preLoaderRoute: typeof TopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  DecksRoute: DecksRoute,
  StudyRoute: StudyRoute,
  TagsRoute: TagsRoute,
  TopicIdRoute: TopicIdRoute,
  TopicNewRoute: TopicNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
